import type { Metadata } from "next";
import { PageShell } from "@/components/page-shell";
import { LegalPage, type LegalSection } from "@/components/legal-page";
import { headers } from "next/headers";

export async function generateMetadata(): Promise<Metadata> { const urdu = (await headers()).get("x-gharmahir-locale") === "ur"; return { title:{ absolute:urdu ? "شرائط و ضوابط | GharMahir لاہور" : "Terms & Conditions | GharMahir Lahore" }, description:urdu ? "GharMahir کی ویب سائٹ درخواستوں اور لاہور میں سولر، الیکٹریکل، اے سی اور گھریلو آلات کی خدمات پر لاگو شرائط۔" : "Terms governing website enquiries and Solar, Electrical, AC and Home Appliance services offered by GharMahir across Lahore.", alternates:{ canonical:urdu ? "/ur/terms-and-conditions" : "/terms-and-conditions", languages:{ en:"/terms-and-conditions", ur:"/ur/terms-and-conditions", "x-default":"/terms-and-conditions" } } }; }

const sections: LegalSection[] = [
  { id:"about", title:"About these terms", paragraphs:["These Terms & Conditions govern [WEBSITE DOMAIN], website and WhatsApp enquiries, quotations, appointments and services supplied by [BUSINESS LEGAL NAME], trading as [TRADING NAME]. By accepting a quotation, you agree to the terms relevant to that work."] },
  { id:"business", title:"Business details", items:["Legal name: [BUSINESS LEGAL NAME]","Trading name: [TRADING NAME]","Address: [BUSINESS ADDRESS]","Registration number: [COMPANY/REGISTRATION NUMBER, IF APPLICABLE]","Email: [EMAIL ADDRESS]","Phone: [PHONE NUMBER]","WhatsApp: [WHATSAPP NUMBER]"] },
  { id:"area", title:"Service area", paragraphs:["Services are intended for Lahore, including DHA, Gulberg, Johar Town, Model Town, Wapda Town, Bahria Town, Valencia, Faisal Town, Garden Town, Cantt, Allama Iqbal Town and Township. Exact coverage, attendance and any travel cost require confirmation."] },
  { id:"services", title:"Services offered", paragraphs:["The website presents Solar, Electrical, AC and Home Appliance services. Availability depends on technician capacity, equipment, parts, site conditions and safety. Every fault, brand, model or location cannot be guaranteed."] },
  { id:"information", title:"Website information", paragraphs:["Website content is general guidance, not a diagnosis, fixed quotation, engineering design or safety certificate. Images may be illustrative. An appropriate inspection may be required."] },
  { id:"enquiries", title:"Website and WhatsApp enquiries", paragraphs:["An enquiry requests a discussion only and does not form a contract. WhatsApp is an independent platform. Suggested messages can be edited and are sent only when the user selects Send. Never share passwords, PINs or banking credentials."] },
  { id:"inspection", title:"Inspection and diagnosis", paragraphs:["Scope, price, parts or feasibility may require inspection. Initial observations can change after safe access, opening or testing. Any visit or diagnostic fee must be disclosed before attendance or in the quotation."] },
  { id:"quotations", title:"Quotations and estimates", paragraphs:["Unless stated otherwise, a quotation is valid for [QUOTATION VALIDITY PERIOD] and covers only its written scope, quantities and included materials. An estimate may change for hidden faults, inaccurate information, price changes or additional approved work."] },
  { id:"agreement", title:"When an agreement is formed", paragraphs:["An agreement forms only when the customer accepts a written quotation or clearly confirmed scope and [TRADING NAME] confirms the appointment or work. Browsing, an automated reply or an unanswered message is not acceptance."] },
  { id:"customer-duties", title:"Customer responsibilities", items:["Provide accurate service, location and access information.","Confirm ownership or authority and obtain landlord, society or building permission.","Disclose known hazards, alterations and equipment history.","Keep children, pets, valuables and unauthorised people away from the work area.","Ensure an authorised adult is available where required."] },
  { id:"safety", title:"Safety and site access", paragraphs:["The customer must provide safe and lawful access to relevant equipment, roofs, boards and utility points. Work may be stopped or postponed for unsafe conditions, unsuitable weather, restricted access or an inability to isolate equipment safely."] },
  { id:"solar", title:"Solar service conditions", paragraphs:["Output depends on design, shade, orientation, weather, cleaning, grid conditions, batteries, settings and usage. Savings, generation, backup duration or payback are not guaranteed unless expressly written. Structural and utility approvals are excluded unless quoted."] },
  { id:"electrical", title:"Electrical service conditions", paragraphs:["Electrical work may require isolation and access to concealed wiring. Unsafe existing wiring, overloading, earthing defects or previous alterations may expand the scope. Unsafe installations will not be energised or certified."] },
  { id:"ac", title:"AC service conditions", paragraphs:["Cooling depends on sizing, refrigerant condition, insulation, airflow, heat load, voltage and installation quality. Gas charging may not resolve leakage. Extra leak testing, parts, drainage or electrical work requires approval when outside scope."] },
  { id:"appliances", title:"Home Appliance service conditions", paragraphs:["Repair depends on brand, model, age, condition, parts and earlier work. Inspection cannot guarantee a successful or economical repair. Customers should back up any data stored by an appliance where relevant."] },
  { id:"materials", title:"Materials and replacement parts", paragraphs:["Important brand, grade, quantity and warranty details should appear in the quotation. Equivalent substitutions need approval. Removed parts remain the customer’s unless disposal is requested or an exchange condition applies."] },
  { id:"changes", title:"Changes and additional work", paragraphs:["Work outside the accepted scope needs a revised quotation or clear customer approval, except immediate reasonable action needed to make a dangerous condition safe. A recorded message may serve as written approval."] },
  { id:"payment", title:"Prices and payment", paragraphs:["Prices, taxes, deposits, milestones and methods appear in the quotation or invoice. Payment is due under those terms, normally with the final balance at completion. Verify account details through an official contact before transfer."], note:"Deposit: [DEPOSIT TERMS]. Payment terms: [PAYMENT TERMS]." },
  { id:"appointments", title:"Appointments and delays", paragraphs:["Times are reasonable estimates and may be affected by traffic, weather, emergencies, earlier jobs, parts or access. Material delays will be communicated where practical, but time is not guaranteed to be of the essence unless agreed in writing."] },
  { id:"cancellation", title:"Cancellation and rescheduling", paragraphs:["Give notice as early as possible. A disclosed visit fee, custom material, non-refundable supplier charge or reasonable cost already incurred may remain payable. Notice period: [CANCELLATION NOTICE PERIOD]."] },
  { id:"completion", title:"Completion and handover", paragraphs:["Work is complete when the accepted scope and reasonable checks or handover are done. Customers should inspect visible work and promptly report concerns. Minor outstanding items that do not prevent safe use do not automatically justify withholding all payment."] },
  { id:"warranties", title:"Workmanship and product warranties", paragraphs:["Any workmanship warranty must be stated in writing as [WORKMANSHIP WARRANTY PERIOD]. Manufacturer warranties follow manufacturer terms. Warranties exclude misuse, damage, unauthorised alteration, unstable supply, external causes, consumables and faults outside scope."] },
  { id:"complaints", title:"Complaints and remedial process", paragraphs:["Send the job reference, address, issue and useful photographs to [EMAIL ADDRESS] or [WHATSAPP NUMBER]. The business should investigate and, where responsible, receive a reasonable opportunity to inspect and remedy before third-party work, except in an emergency."] },
  { id:"liability", title:"Liability", paragraphs:["Nothing excludes liability that cannot legally be excluded. Subject to law, [TRADING NAME] is not responsible for indirect loss or loss caused by inaccurate information, pre-existing defects, third-party work, misuse, utility failure or events beyond reasonable control. Proposed cap: [LIABILITY CAP—LEGAL REVIEW REQUIRED]."], note:"A qualified Pakistani legal professional must review this limitation before publication." },
  { id:"third-party-products", title:"Third-party products and manufacturers", paragraphs:["Product specifications, apps, cloud services, utility connections and manufacturer support are controlled by third parties. [TRADING NAME] cannot guarantee continued availability, compatibility or third-party performance."] },
  { id:"ai-images", title:"Illustrative and AI-assisted images", paragraphs:["Some images may be AI-generated or enhanced to illustrate service environments. They are not proof of a particular project, technician, brand, result or customer unless clearly identified and authorised."] },
  { id:"acceptable-use", title:"Acceptable website use", items:["Do not disrupt, probe, overload or access systems without authority.","Do not submit unlawful, abusive, misleading or malicious material.","Do not impersonate anyone or enquire without authority.","Do not unlawfully copy, scrape or republish website content."] },
  { id:"ip", title:"Intellectual property", paragraphs:["Website text, layout, graphics, branding and original media are owned by or licensed to [TRADING NAME], excluding third-party marks. Personal viewing is allowed; commercial reproduction or modification requires written permission."] },
  { id:"links", title:"Third-party links", paragraphs:["Links such as WhatsApp and Facebook are for convenience. [TRADING NAME] does not control their content, privacy, security, availability or terms."] },
  { id:"force-majeure", title:"Events beyond reasonable control", paragraphs:["Neither party is responsible for delay caused by events reasonably outside its control, including severe weather, flood, fire, civil disturbance, restriction, utility interruption, transport disruption, shortages or widespread network failure."] },
  { id:"refusal", title:"Right to refuse or stop work", paragraphs:["Work may be refused, suspended or stopped for unsafe conditions, threats, suspected illegality, non-payment, material misinformation, unavailable parts, work outside competence or missing permission. Authorised work already completed may remain payable."] },
  { id:"law", title:"Governing law and disputes", paragraphs:["These terms are intended to follow applicable Pakistan law and mandatory rights. Parties should first attempt good-faith resolution through the complaints process. A court or lawful forum with jurisdiction in Lahore, Punjab will apply, subject to legal review."] },
  { id:"general", title:"Severability, waiver and entire agreement", paragraphs:["An invalid provision does not invalidate the remainder. Delayed enforcement is not a waiver. The accepted quotation, confirmed changes and these terms form the agreement for the work and replace earlier statements about that scope."] },
  { id:"term-updates", title:"Changes to these terms", paragraphs:["Terms may change for operational, service or legal reasons. The version in force when a quotation is accepted normally governs that job unless later agreed or legally required. Effective: [EFFECTIVE DATE]. Updated: [LAST UPDATED DATE]."] },
  { id:"contact", title:"Contact us", items:["[BUSINESS LEGAL NAME], trading as [TRADING NAME]","Address: [BUSINESS ADDRESS]","Email: [EMAIL ADDRESS]","Phone: [PHONE NUMBER]","WhatsApp: [WHATSAPP NUMBER]","Website: [WEBSITE DOMAIN]"] },
];

export default function TermsPage(){ return <PageShell><LegalPage eyebrow="Service & website terms" title="Terms & Conditions" introduction="The terms that apply when you browse our website, request a quotation or arrange Solar, Electrical, AC or Home Appliance work in Lahore." sections={sections}/></PageShell>; }
