import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { PageShell } from "@/components/page-shell";
import { headers } from "next/headers";

export async function generateMetadata(): Promise<Metadata> { const urdu = (await headers()).get("x-gharmahir-locale") === "ur"; return { title:urdu ? "لاہور میں سروس پروجیکٹس" : "Service Project Gallery in Lahore", description:urdu ? "لاہور کے گھروں اور کاروباری جگہوں کے سولر، الیکٹریکل، اے سی اور گھریلو آلات کے نمائندہ پروجیکٹس دیکھیں۔" : "Explore representative Solar, Electrical, AC and Home Appliance project scopes for Lahore homes and businesses.", alternates:{ canonical:urdu ? "/ur/projects" : "/projects", languages:{ en:"/projects", ur:"/ur/projects", "x-default":"/projects" } } }; }

const projects = [
  { category: "Solar Services", area: "DHA, Lahore", title: "Residential Rooftop Solar Setup", image: "/images/projects/lahore-rooftop-solar-project.webp", alt: "Completed rooftop solar panel array on a Lahore house with no people present", href: "/services/solar", accent: "solar", summary: "A clean rooftop layout planned around usable roof space, sunlight exposure, safe access and organised cable routing.", scope: ["Rooftop layout review", "Panel mounting arrangement", "Protected cable route", "System testing plan"], result: "An organised panel layout that keeps maintenance access and surrounding rooftop use in view." },
  { category: "Electrical Services", area: "Johar Town, Lahore", title: "Distribution Board Upgrade", image: "/images/projects/lahore-electrical-db-project.webp", alt: "Organised residential distribution board and circuit breakers in a Lahore home", href: "/services/electrical", accent: "electrical", summary: "A residential distribution-board improvement focused on circuit organisation, protection and easier future maintenance.", scope: ["Existing-load review", "Breaker arrangement", "Circuit organisation", "Connection testing"], result: "A cleaner board layout with accessible circuits and a more understandable protection arrangement." },
  { category: "AC Services", area: "Gulberg, Lahore", title: "Split AC Installation", image: "/images/projects/lahore-ac-installation-project.webp", alt: "Completed split air conditioner installation in a modern Lahore living room", href: "/services/ac", accent: "ac", summary: "A finished split-AC installation with considered indoor placement, concealed routing and a tidy interior finish.", scope: ["Placement assessment", "Secure indoor mounting", "Pipe and drain routing", "Cooling-performance check"], result: "A neat installation designed around room airflow, drainage and practical service access." },
  { category: "Home Appliance Services", area: "Model Town, Lahore", title: "Home Appliance Setup Review", image: "/images/projects/lahore-home-appliance-project.webp", alt: "Modern Lahore kitchen with refrigerator, microwave, water dispenser, oven and washing machine", href: "/services/home-appliances", accent: "appliances", summary: "A coordinated kitchen and utility-appliance setup review covering placement, power access and safe day-to-day operation.", scope: ["Appliance placement review", "Power-point assessment", "Ventilation and access", "Operational checks"], result: "Essential appliances arranged for practical use, ventilation and straightforward future maintenance." },
] as const;

export default function ProjectsPage() {
  return <PageShell><section className="projectsHero"><div className="container projectsHeroInner"><span className="eyebrow">Project gallery</span><h1>Service work shaped around real Lahore properties.</h1><p>Explore representative project scopes across Solar, Electrical, AC and Home Appliance services. Every final scope depends on the actual property, equipment and site assessment.</p><div className="projectsHeroStats"><div><strong>4</strong><span>Service categories</span></div><div><strong>Lahore</strong><span>Local property focus</span></div><div><strong>Clear</strong><span>Assessment-led scope</span></div></div></div></section><section className="projectsGallerySection"><div className="container"><div className="projectsHeading"><div><span className="eyebrow">Selected work</span><h2>Project Showcases</h2></div><p>Each example highlights the type of planning, inspection and finishing considered for a professional service outcome.</p></div><div className="projectsGrid">{projects.map((project, index) => <article className={`projectShowcase project-${project.accent}`} key={project.title}><div className="projectShowcaseImage"><Image src={project.image} alt={project.alt} fill priority={index < 2} sizes="(max-width: 760px) 100vw, 50vw" /><span>{String(index + 1).padStart(2, "0")}</span></div><div className="projectShowcaseBody"><div className="projectMeta"><span>{project.category}</span><span>{project.area}</span></div><h2>{project.title}</h2><p>{project.summary}</p><div className="projectScope"><h3>Scope highlights</h3><ul>{project.scope.map((item) => <li key={item}><span aria-hidden="true">✓</span>{item}</li>)}</ul></div><div className="projectResult"><span>Project outcome</span><p>{project.result}</p></div><div className="projectActions"><Link className="button secondary" href={project.href}>Explore {project.category}</Link></div></div></article>)}</div></div></section><section className="projectsNote"><div className="container projectsNoteInner"><span aria-hidden="true">i</span><div><h2>Every property needs its own assessment.</h2><p>These showcases illustrate typical service scope. Equipment selection, materials, access, pricing and completion requirements are confirmed only after reviewing the actual site.</p></div></div></section><section className="final projectsFinal"><div className="container"><span className="eyebrow">Plan your requirement</span><h2>Have a similar project in Lahore?</h2><p>Explore the relevant service category to review available support for your property.</p><Link className="button secondary" href="/#services">Explore Services</Link></div></section></PageShell>;
}
