import type { Metadata } from "next";
import { PageShell } from "@/components/page-shell";
import { LegalPage, type LegalSection } from "@/components/legal-page";
import { headers } from "next/headers";

export async function generateMetadata(): Promise<Metadata> { const urdu = (await headers()).get("x-gharmahir-locale") === "ur"; return { title:{ absolute:urdu ? "رازداری کی پالیسی | GharMahir لاہور" : "Privacy Policy | GharMahir Lahore" }, description:urdu ? "جانیں کہ GharMahir لاہور کی ہوم سروس ویب سائٹ اور واٹس ایپ درخواستوں سے موصول معلومات کو کیسے استعمال اور محفوظ کرتا ہے۔" : "Learn how GharMahir collects, uses, stores and protects information submitted through its Lahore home-services website and WhatsApp enquiry channels.", alternates:{ canonical:urdu ? "/ur/privacy-policy" : "/privacy-policy", languages:{ en:"/privacy-policy", ur:"/ur/privacy-policy", "x-default":"/privacy-policy" } } }; }

const sections: LegalSection[] = [
  { id:"introduction", title:"Introduction", paragraphs:["This Privacy Policy explains how [BUSINESS LEGAL NAME], trading as [TRADING NAME], handles personal information when people browse [WEBSITE DOMAIN], select a service, click a WhatsApp button, send an enquiry, share location or property details, provide service photographs or videos, schedule an inspection, receive a quotation, or request or receive Solar, Electrical, AC or Home Appliance services.","WhatsApp is a separate third-party platform governed by its own privacy terms. This website creates a link to WhatsApp but does not control WhatsApp’s independent processing."], note:"This policy should be read alongside the applicable service Terms & Conditions." },
  { id:"information-collected", title:"Information we may collect", paragraphs:["We should collect only information reasonably required to manage enquiries, operate and secure the website, prepare service recommendations and provide approved work."], items:["Information provided directly: name, phone or WhatsApp number, email address, Lahore area, property or service location, selected service, issue description and preferred appointment time.","Service material: relevant equipment or property photographs and videos, messages, communication history, quotation and service records, feedback and complaint details.","Website information: IP address, browser and device type, operating system, pages viewed, referral source, approximate IP-derived location where available, visit date and time, and error or security logs.","Cookie or analytics identifiers would be collected only if an analytics tool requiring them is introduced and appropriately disclosed."] },
  { id:"collection-methods", title:"How information is collected", paragraphs:["Information may be collected through an enabled website contact form, WhatsApp conversations, phone calls, email enquiries, inspection or appointment records, customer-provided media, and server or security logs."], items:["The contact form currently asks for service type, Lahore area, a message and consent; delivery to an external webhook occurs only when ENQUIRY_WEBHOOK_URL is configured.","Clicking a wa.me link opens WhatsApp with a suggested message. The user may review, change or delete that message, and nothing is sent until the user confirms it in WhatsApp.","Cookies or analytics tools will be described here if introduced in future."] },
  { id:"purposes", title:"Purposes for using information", items:["Respond to enquiries and identify the selected service.","Understand a reported problem and arrange an inspection or appointment.","Prepare a quotation and provide the approved service.","Communicate about scheduling, delays, access and handover.","Maintain appropriate enquiry, quotation, service, complaint and support records.","Improve website content and understand basic website performance.","Prevent fraud, misuse and security threats.","Meet applicable legal requirements and establish or defend legal claims."], note:"[TRADING NAME] does not state that customer information is sold. Information must not be sold or shared for unrelated independent marketing without appropriate permission." },
  { id:"fair-processing", title:"Lawful and fair processing", paragraphs:["Information will be handled transparently, with the individual’s knowledge or consent where appropriate, to respond to a requested service, carry out agreed service arrangements, support legitimate operational and security needs, or comply with applicable law.","This policy does not claim GDPR compliance. The business should obtain advice if it intentionally targets or processes individuals in jurisdictions with additional requirements. Pakistan’s proposed or draft personal-data legislation is not described here as enacted law; applicable Pakistan and Punjab requirements should be confirmed through legal advice."] },
  { id:"whatsapp", title:"WhatsApp and third-party communication", paragraphs:["WhatsApp is operated independently. It may process phone numbers, messages and technical information under its own policies. The website controls only the link and suggested text, and no message is sent until the user chooses Send in WhatsApp."], items:["Do not send passwords, PINs, one-time passwords, banking credentials, identity documents or unrelated private information.","Sensitive information should be requested only where genuinely necessary and through an appropriate channel.","Service messages may remain in WhatsApp accounts and devices according to account settings and platform rules."] },
  { id:"cookies", title:"Cookies and analytics", paragraphs:["The inspected codebase does not currently install a third-party analytics, advertising or marketing SDK and does not set non-essential cookies. It uses an in-page dataLayer/event interface for local interaction events, but no external analytics destination is configured in the code reviewed. Accordingly, no cookie-consent banner is presented at this time."], items:["Essential cookies support necessary security or website operation.","Preference cookies remember optional choices.","Analytics cookies measure visits and behaviour.","Marketing cookies support advertising or cross-site profiling."], note:"If non-essential analytics, preference or marketing cookies are introduced, this policy and consent controls must be updated before those tools load." },
  { id:"sharing", title:"Sharing of information", paragraphs:["Information may be shared only where reasonably necessary with employees or authorised technicians, contractors directly involved in the requested service, website hosting and technical providers, communication providers such as WhatsApp, a configured enquiry-delivery provider, professional advisers, and government or law-enforcement authorities where legally required."], note:"The business has not confirmed that every technician is an employee. Access should be limited to people who need the information for the requested work." },
  { id:"photographs", title:"Customer photographs and property information", paragraphs:["Customers may send images to help explain a service requirement. Images should show only relevant equipment or property areas and should avoid faces, identity cards, personal documents, children, valuables and unrelated private spaces.","Customer images are not automatically public. Property photographs must not be used for advertising or a project gallery without separate appropriate permission, and private addresses or identifying details should be removed before publication."] },
  { id:"security", title:"Data storage and security", paragraphs:["Reasonable safeguards may include restricted access, secure hosting, access controls, password protection, software updates, encrypted HTTPS connections, backups, logging, monitoring and deletion when information is no longer required.","No internet transmission, device, account or storage system can be guaranteed completely secure. The business therefore cannot promise absolute security and should review access and provider settings regularly."] },
  { id:"retention", title:"Data retention", paragraphs:["Information should be retained only as long as reasonably required for enquiry follow-up, service delivery, customer support, complaints, accounting or business records, legal obligations, security and dispute resolution. The business-approved general period is [DATA RETENTION PERIOD].","Different records may require different periods. Information should be securely deleted or anonymised when no continuing purpose or legal requirement applies."] },
  { id:"international-processing", title:"International or cloud processing", paragraphs:["Hosting, email, enquiry delivery, analytics if later enabled, and WhatsApp providers may process information on servers outside Pakistan. Provider locations can change and are not assumed in this policy.","Where applicable, [TRADING NAME] will use reasonable contractual, organisational and technical safeguards appropriate to the service and information involved."] },
  { id:"choices", title:"Your choices and requests", paragraphs:["A person may ask for confirmation of information held, correction of inaccurate information, deletion where legally and operationally possible, withdrawal from optional marketing, clarification about use, or review of a data-handling complaint. Requests may be sent to [EMAIL ADDRESS] or [WHATSAPP NUMBER].","Identity may need to be reasonably verified. Some information may be retained for legal, accounting, fraud-prevention, safety or dispute purposes even after a deletion request."] },
  { id:"marketing", title:"Marketing communications", paragraphs:["Replies about an enquiry, quotation, inspection or active appointment are service communications, not promotional marketing. Optional promotional messages should be sent only where appropriate permission exists, and recipients may ask for them to stop.","Submitting a service enquiry does not automatically subscribe a person to marketing. Required service-related messages may still be sent while an enquiry or appointment remains active."] },
  { id:"children", title:"Children’s privacy", paragraphs:["The website is intended for adults arranging property-related services. [TRADING NAME] does not knowingly seek personal information from children. A parent or guardian should contact [EMAIL ADDRESS] or [WHATSAPP NUMBER] if a child has submitted information so the circumstances can be reviewed."] },
  { id:"external-links", title:"Third-party links", paragraphs:["The website may link to WhatsApp, maps, social platforms or other external sites. Those services have separate policies, security practices and availability. Users should review the relevant third-party terms before providing information."] },
  { id:"incidents", title:"Data incidents", paragraphs:["The business will investigate suspected incidents, take reasonable containment steps, preserve appropriate records, and notify affected people or authorities where required by applicable law and the circumstances. No fixed notification deadline is promised here without confirmed legal requirements and advice."] },
  { id:"updates", title:"Policy updates", paragraphs:["This policy may be updated when services, website features, technology providers or applicable legal requirements change. The effective date [EFFECTIVE DATE] and last-updated date [LAST UPDATED DATE] should be completed and revised whenever a material change is published."] },
  { id:"contact", title:"Contact and privacy enquiries", paragraphs:["For privacy questions, requests or complaints, use the dedicated subject line “Privacy enquiry” and contact the business using the verified details below."], items:["Legal name: [BUSINESS LEGAL NAME]","Trading name: [TRADING NAME]","Business address: [BUSINESS ADDRESS]","Company/registration number: [COMPANY/REGISTRATION NUMBER, IF APPLICABLE]","Email: [EMAIL ADDRESS]","Phone: [PHONE NUMBER]","WhatsApp: [WHATSAPP NUMBER]","Website: [WEBSITE DOMAIN]"] },
];

export default function PrivacyPage(){return <PageShell><LegalPage eyebrow="Privacy & data handling" title="Privacy Policy" introduction="A plain-language explanation of how information is handled across our Lahore service website, contact form and WhatsApp enquiry journey." sections={sections}/></PageShell>}
