import Image from "next/image";
import Link from "next/link";
import { PageShell } from "@/components/page-shell";
import { WhatsAppLink } from "@/components/whatsapp-link";

const serviceCards = [
  { key: "solar", icon: "☀", name: "Solar Services", detail: "Solar Panel Installation", href: "/services/solar/panel-installation", image: "/images/solar-panel-installation-lahore.webp", alt: "Solar technicians installing rooftop panels in Lahore", description: "Installation, setup, diagnostics, inverter and battery support for homes and businesses." },
  { key: "electrical", icon: "⌁", name: "Electrical Services", detail: "Electrical Wiring", href: "/services/electrical/new-wiring", image: "/images/electrical-wiring-lahore.webp", alt: "Electrician performing organised residential wiring in Lahore", description: "Safe wiring, fault repair, distribution board work and electrical upgrades." },
  { key: "ac", icon: "❄", name: "AC Services", detail: "AC Installation", href: "/services/ac/installation", image: "/images/ac-installation-lahore.webp", alt: "AC technician installing a split AC unit in a Lahore home", description: "Professional installation, repair, maintenance, shifting and cooling diagnostics." },
];

export default function HomePage() {
  return <PageShell>
    <section className="hero heroFull"><Image className="heroBackground" src="/images/lahore-solar-rooftop-hero-v2.webp" alt="Professional Pakistani technicians installing solar panels on a Lahore rooftop" fill priority sizes="100vw" /><div className="heroOverlay" aria-hidden="true" /><div className="container heroContent"><span className="eyebrow heroLabel">Professional Home &amp; Business Services in Lahore</span><h1>Reliable <span>Solar, Electrical &amp; AC</span> Services in Lahore</h1><p className="lead">From solar panel installation and system repairs to professional electrical and AC services, get dependable support for your home or business.</p><div className="actions heroActions"><WhatsAppLink position="hero">Contact on WhatsApp</WhatsAppLink><Link className="button secondary heroSecondary" href="#services">Explore Our Services</Link></div><p className="heroTrust">Professional Assessment <b>•</b> Clear Quotation <b>•</b> Reliable Support</p></div></section>
    <section id="services" className="servicesSection"><div className="container"><div className="servicesHeading"><span className="eyebrow">What we do</span><h2>Our Services</h2><p>Professional Solar, Electrical and AC services for homes and businesses across Lahore.</p></div><div className="serviceCardGrid">{serviceCards.map((service) => <article className={`serviceCard ${service.key === "solar" ? "featuredService" : ""}`} key={service.key}><div className="serviceImage"><Image src={service.image} alt={service.alt} fill sizes="(max-width: 720px) 100vw, (max-width: 1100px) 50vw, 33vw" /></div><div className="serviceCardBody"><div className="serviceIcon" aria-hidden="true">{service.icon}</div><h3>{service.name}</h3><p>{service.description}</p><div className="serviceCardActions"><Link className="button secondary" href={service.href}>View Details</Link><WhatsAppLink service={service.detail} position="service_card">Contact on WhatsApp for {service.detail}</WhatsAppLink></div></div></article>)}</div></div></section>
    <section className="soft"><div className="container split"><div><span className="eyebrow">How it works</span><h2>Clear from first message to handover.</h2><p>Tell us your area, share photos if helpful, and we will confirm the appropriate next step before a final quotation.</p><WhatsAppLink position="process">Contact on WhatsApp</WhatsAppLink></div><div className="steps">{["Share details", "Assess", "Explain scope", "Complete work", "Test and hand over"].map((step, index) => <div className="step" key={step}><div className="stepNumber">{index + 1}</div><h3>{step}</h3></div>)}</div></div></section>
    <section className="final"><div className="container"><span className="eyebrow" style={{ color: "#F5B82E" }}>WhatsApp-first support</span><h2>Tell us what you need and where you are in Lahore.</h2><p>Share your service requirement, area and any helpful photos. We will confirm the next step.</p><div className="actions" style={{ justifyContent: "center" }}><WhatsAppLink position="final_cta">Contact on WhatsApp</WhatsAppLink><Link className="button secondary" href="/contact">Contact options</Link></div></div></section>
  </PageShell>;
}
