import Link from "next/link";
import { PageShell } from "@/components/page-shell";
import { WhatsAppLink } from "@/components/whatsapp-link";
import { services } from "@/lib/site";

const icons = { solar: "☀", electrical: "⌁", ac: "❄" };

export default function HomePage() {
  return <PageShell><section className="hero"><div className="container heroGrid"><div><span className="eyebrow">Lahore service team</span><h1>Solar, electrical and AC work—done with care.</h1><p className="lead">Clear assessment, written quotation and dependable support for homes, shops and offices in confirmed Lahore service areas.</p><div className="actions"><WhatsAppLink>Request a consultation</WhatsAppLink><Link className="button secondary" href="#services">Explore services</Link></div><div className="proof"><span><strong>Site assessment</strong>before final quotation</span><span><strong>Written scope</strong>for clear expectations</span><span><strong>After-service support</strong>where applicable</span></div></div><div className="heroVisual" role="img" aria-label="Placeholder for approved solar project photography"><div className="visualNote"><span className="tag" style={{ color: "#F5B82E" }}>Approved project image placeholder</span><h2>Real Lahore project proof belongs here</h2></div></div></div></section>
    <section id="services"><div className="container"><div className="sectionTop"><div><span className="eyebrow">Our services</span><h2>One team for essential property systems.</h2></div><p>Choose the service that matches your need. Each route keeps the conversation simple with a service-specific WhatsApp enquiry.</p></div><div className="grid3">{(Object.keys(services) as Array<keyof typeof services>).map((key) => { const service = services[key]; return <article key={key} className={`card ${key === "solar" ? "featured" : ""}`}><div className="icon">{icons[key]}</div><h3>{service.label} services</h3><p>{service.description}</p><Link className="textLink" href={service.href}>View details →</Link><WhatsAppLink service={service.label} className="textLink">WhatsApp about {service.label.toLowerCase()} →</WhatsAppLink></article>; })}</div></div></section>
    <section className="soft"><div className="container split"><div><span className="eyebrow">Solar spotlight</span><h2>Plan the right solar solution for your property.</h2><p>We begin with your site, load requirements and existing equipment—then outline a practical scope before any final quotation.</p><ul className="list"><li>Installation and system connection</li><li>Repair, diagnosis and performance checks</li><li>Inverter, battery and upgrade guidance</li></ul><WhatsAppLink service="solar services">Discuss a solar project</WhatsAppLink></div><div className="card"><span className="tag">Trust through process</span><h3>Assessment before recommendation</h3><p>Service pages explain the work included, likely warning signs, testing steps and handover expectations in plain language.</p><WhatsAppLink service="solar services" className="textLink">Request a WhatsApp consultation →</WhatsAppLink></div></div></section>
    <section><div className="container"><div className="sectionTop"><div><span className="eyebrow">How it works</span><h2>Clear from first message to handover.</h2></div></div><div className="steps">{[["Select service","Start with solar, electrical or AC."],["Share details","Send your area, photos and urgency."],["Assess","We review the site or diagnose the issue."],["Quote","Receive a written scope and quotation."],["Complete","Work, testing and support follow."]].map(([title,text], index) => <div className="step" key={title}><div className="stepNumber">{index + 1}</div><h3>{title}</h3><p>{text}</p></div>)}</div></div></section>
    <section className="soft"><div className="container"><div className="sectionTop"><div><span className="eyebrow">Project evidence</span><h2>Recent work, shown with useful context.</h2></div><p>Launch cards will use only approved project images and confirmed Lahore areas.</p></div><div className="grid3">{[["Solar","Residential solar installation",""],["Electrical","Electrical upgrade","electrical"],["AC","AC service and repair","ac"]].map(([type,title,style]) => <article className="card" key={title}><div className={`projectVisual ${style}`} /><span className="tag">{type} · Area pending</span><h3>{title}</h3><p>Challenge, completed scope and result placeholder.</p></article>)}</div></div></section>
    <section><div className="container"><div className="sectionTop"><div><span className="eyebrow">Common questions</span><h2>Answers before you contact us.</h2></div></div><details className="faq"><summary>How is the final quotation decided?</summary><p>It depends on site condition, required materials, equipment compatibility and complete work scope.</p></details><details className="faq"><summary>Which Lahore areas do you serve?</summary><p>Only confirmed service areas will be listed once the business owner provides the final coverage list.</p></details><details className="faq"><summary>Can I send photos before an inspection?</summary><p>Yes. The WhatsApp journey asks for your area, photos, urgency and a brief description of the work.</p></details></div></section>
    <section className="final"><div className="container"><span className="eyebrow" style={{ color: "#F5B82E" }}>WhatsApp-first support</span><h2>Tell us what you need and where you are in Lahore.</h2><p>Share your service requirement, area and any helpful photos. We will confirm the next step.</p><div className="actions" style={{ justifyContent: "center" }}><WhatsAppLink className="button primary">Start WhatsApp enquiry</WhatsAppLink><Link className="button secondary" href="/contact">Contact options</Link></div></div></section></PageShell>;
}
