"use client";

import { FormEvent, useState } from "react";
import { track } from "@/lib/analytics";

export function ContactForm() {
  const [notice, setNotice] = useState(""); const [error, setError] = useState(""); const [sending, setSending] = useState(false);
  async function handleSubmit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setNotice(""); setError(""); const form = new FormData(event.currentTarget); const payload = Object.fromEntries(form.entries()); if (payload.consent !== "on") { setError("Please confirm consent before sending."); return; } setSending(true); try { const response = await fetch("/api/enquiry", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...payload, consent: true }) }); const data = await response.json() as { ok?: boolean; error?: string; delivery?: string }; if (!response.ok || !data.ok) throw new Error(data.error || "Unable to submit the enquiry."); track({ event: "contact_form_submit", page_path: window.location.pathname, service: String(payload.service), area: String(payload.area) }); setNotice(data.delivery === "sent" ? "Your enquiry has been sent." : "Form delivery is not connected yet. Please use WhatsApp for a faster response."); } catch (submissionError) { setError(submissionError instanceof Error ? submissionError.message : "Unable to submit the enquiry."); } finally { setSending(false); } }
  return <form className="form" onSubmit={handleSubmit} onFocus={() => track({ event: "contact_form_start", page_path: window.location.pathname, service: "unknown" })}><input name="website" className="honeypot" tabIndex={-1} autoComplete="off" aria-hidden="true" /><div className="formGrid"><label className="field">Service<select name="service" defaultValue="" required><option value="" disabled>Select service</option><option>Solar</option><option>Electrical</option><option>AC</option></select></label><label className="field">Lahore area<input name="area" placeholder="Your area" autoComplete="address-level2" required /></label></div><label className="field">Your requirement<textarea name="message" rows={5} minLength={10} maxLength={2000} placeholder="Briefly describe the work you need" required /></label><label className="consent"><input name="consent" type="checkbox" /> I agree that my enquiry details may be used to respond to this request.</label><button className="button primary" type="submit" disabled={sending}>{sending ? "Sending…" : "Send enquiry"}</button>{notice && <small className="success" role="status">{notice}</small>}{error && <small className="error" role="alert">{error}</small>}<small className="muted">WhatsApp remains the fastest contact option.</small></form>;
}
