import Image from "next/image";

const projects = [
  { accent:"solar", category:"Solar Services", title:"Residential Rooftop Solar Setup", area:"DHA, Lahore", image:"/images/projects/lahore-rooftop-solar-project.webp", alt:"Completed rooftop solar panel project in Lahore", description:"A clean rooftop layout planned around usable roof space, sunlight exposure, safe access and organised cable routing.", scope:["Rooftop layout review","Panel mounting arrangement","Protected cable route","System testing plan"], result:"An organised panel layout that keeps maintenance access and surrounding rooftop use in view.", urCategory:"سولر سروسز", urTitle:"رہائشی چھت پر سولر سسٹم", urDescription:"دھوپ، محفوظ رسائی اور منظم کیبل روٹ کے مطابق تیار کیا گیا صاف ستھرا سولر لے آؤٹ۔", urScope:["چھت کے لے آؤٹ کا جائزہ","پینل ماؤنٹنگ کی ترتیب","محفوظ کیبل روٹ","سسٹم ٹیسٹنگ پلان"], urResult:"ایک منظم پینل لے آؤٹ جس میں دیکھ بھال کی رسائی اور چھت کے استعمال کو مدِنظر رکھا گیا۔" },
  { accent:"electrical", category:"Electrical Services", title:"Distribution Board Upgrade", area:"Johar Town, Lahore", image:"/images/projects/lahore-electrical-db-project.webp", alt:"Organised distribution board project in Lahore", description:"A residential distribution-board improvement focused on circuit organisation, protection and easier future maintenance.", scope:["Existing-load review","Breaker arrangement","Circuit organisation","Connection testing"], result:"A cleaner board layout with accessible circuits and a more understandable protection arrangement.", urCategory:"الیکٹریکل سروسز", urTitle:"ڈسٹری بیوشن بورڈ اپ گریڈ", urDescription:"سرکٹ کی تنظیم، حفاظت اور آئندہ دیکھ بھال کو مدِنظر رکھ کر کیا گیا بورڈ اپ گریڈ۔", urScope:["موجودہ لوڈ کا جائزہ","بریکر کی ترتیب","سرکٹ کی تنظیم","کنکشن کی جانچ"], urResult:"آسان رسائی والے سرکٹس اور واضح حفاظتی ترتیب کے ساتھ صاف ستھرا بورڈ لے آؤٹ۔" },
  { accent:"ac", category:"AC Services", title:"Split AC Installation", area:"Gulberg, Lahore", image:"/images/projects/lahore-ac-installation-project.webp", alt:"Completed split AC installation project in Lahore", description:"A finished split-AC installation with considered indoor placement, concealed routing and a tidy interior finish.", scope:["Placement assessment","Secure indoor mounting","Pipe and drain routing","Cooling-performance check"], result:"A neat installation designed around room airflow, drainage and practical service access.", urCategory:"اے سی سروسز", urTitle:"اسپلٹ اے سی کی تنصیب", urDescription:"کمرے میں جگہ، پوشیدہ پائپ روٹ اور صاف تکمیل کے ساتھ مکمل اسپلٹ اے سی تنصیب۔", urScope:["جگہ کا جائزہ","محفوظ اِن ڈور ماؤنٹنگ","پائپ اور ڈرین روٹ","کولنگ کی جانچ"], urResult:"ہوا کے بہاؤ، نکاسی اور سروس رسائی کے مطابق صاف ستھری تنصیب۔" },
  { accent:"appliances", category:"Home Appliance Services", title:"Home Appliance Setup Review", area:"Model Town, Lahore", image:"/images/projects/lahore-home-appliance-project.webp", alt:"Modern home appliance setup project in Lahore", description:"A coordinated kitchen and utility-appliance setup review covering placement, power access and safe day-to-day operation.", scope:["Appliance placement review","Power-point assessment","Ventilation and access","Operational checks"], result:"Essential appliances arranged for practical use, ventilation and straightforward future maintenance.", urCategory:"گھریلو برقی آلات", urTitle:"گھریلو آلات کے سیٹ اَپ کا جائزہ", urDescription:"آلات کی جگہ، بجلی کی رسائی اور محفوظ روزمرہ استعمال کا منظم جائزہ۔", urScope:["آلات کی جگہ کا جائزہ","پاور پوائنٹ کی جانچ","ہوا اور رسائی","آپریشنل جانچ"], urResult:"عملی استعمال، ہوا کی آمدورفت اور آسان دیکھ بھال کے لیے ضروری آلات کی مناسب ترتیب۔" }
];

export function HomeProjects({ locale = "en" }: { locale?: "en" | "ur" }) {
  const urdu = locale === "ur";
  return <section className="homeProjectsSection"><div className="container">
    <div className="catalogueIntro homeProjectsHeading"><span className="eyebrow">{urdu ? "منتخب کام" : "Selected work"}</span><h2>{urdu ? "ہمارے پروجیکٹس" : "Our Projects"}</h2><p>{urdu ? "لاہور کی پراپرٹیز کے لیے منصوبہ بندی، معائنے اور صاف تکمیل کے ساتھ مکمل کیے گئے نمائندہ سروس پروجیکٹس۔" : "Representative service projects showing the planning, inspection and finishing considered for Lahore properties."}</p></div>
    <div className="homeProjectsGrid">{projects.map((project, index) => <article className={`projectShowcase project-${project.accent}`} key={project.title}><div className="projectShowcaseImage"><Image src={project.image} alt={urdu ? `${project.urTitle}، لاہور` : project.alt} fill sizes="(max-width: 760px) 100vw, 50vw" /><span>{String(index + 1).padStart(2,"0")}</span></div><div className="projectShowcaseBody"><div className="projectMeta"><span>{urdu ? project.urCategory : project.category}</span><span>{project.area}</span></div><h2>{urdu ? project.urTitle : project.title}</h2><p>{urdu ? project.urDescription : project.description}</p><div className="projectScope"><h3>{urdu ? "کام کی اہم تفصیل" : "Scope highlights"}</h3><ul>{(urdu ? project.urScope : project.scope).map((item) => <li key={item}><span aria-hidden="true">✓</span>{item}</li>)}</ul></div><div className="projectResult"><span>{urdu ? "پروجیکٹ کا نتیجہ" : "Project outcome"}</span><p>{urdu ? project.urResult : project.result}</p></div></div></article>)}</div>
  </div></section>;
}
