export type ServiceDetail = {
  category: "solar" | "electrical" | "ac" | "home-appliances";
  title: string;
  summary: string;
  image: string;
  imageAlt: string;
  overview: string;
  includes: string[];
  commonNeeds: string[];
  checks?: readonly string[];
  gallery: { src: string; alt: string }[];
};

const categoryData = {
  solar: {
    installImage: "/images/solar-panel-installation-lahore.webp",
    repairImage: "/images/solar-inverter-repair-lahore.webp",
    installAlt: "Solar technicians installing rooftop panels in Lahore",
    repairAlt: "Technician inspecting solar inverter equipment in Lahore",
    checks: ["Roof access, usable area and shading", "Equipment model and system compatibility", "Cable routes, protection and earthing", "Displayed system status and visible connections"],
  },
  electrical: {
    installImage: "/images/electrical-wiring-lahore.webp",
    repairImage: "/images/electrical-fault-repair-lahore.webp",
    installAlt: "Electrician installing organised residential wiring in Lahore",
    repairAlt: "Electrician diagnosing a distribution board in Lahore",
    checks: ["Expected loads and affected circuits", "Cable, point and termination condition", "Distribution board and breaker arrangement", "Earthing and visible signs of heat or damage"],
  },
  ac: {
    installImage: "/images/ac-installation-lahore.webp",
    repairImage: "/images/ac-repair-service-lahore.webp",
    installAlt: "AC technician installing a split AC in a Lahore home",
    repairAlt: "AC technician diagnosing cooling performance in Lahore",
    checks: ["Indoor and outdoor unit condition", "Airflow, controls and visible electrical parts", "Drain, pipe route and accessible joints", "Mounting, ventilation and service access"],
  },
  "home-appliances": {
    installImage: "/images/home-appliances/category-hero.webp",
    repairImage: "/images/home-appliances/refrigerator-repair.webp",
    installAlt: "Home appliance technician servicing household appliances in Lahore",
    repairAlt: "Technician diagnosing a refrigerator in a Lahore home",
    checks: ["Appliance model, symptoms and fault history", "Power supply, controls and accessible wiring", "Visible mechanical parts, seals, hoses and drainage", "Safe testing and repair options before parts are changed"],
  },
} as const;

type Entry = Omit<ServiceDetail, "image" | "imageAlt" | "gallery"> & { imageType: "install" | "repair"; customImage?: string; customAlt?: string };

const entries: Record<string, Entry> = {
  "solar/panel-installation": { category: "solar", title: "Solar Panel Installation", imageType: "install", summary: "Site-led rooftop solar planning and installation for homes, shops and offices.", overview: "Panel layout should reflect usable roof area, shading, orientation, daytime load and compatible system equipment. The final layout is confirmed after assessment.", includes: ["Roof and usable-area review", "Panel layout and mounting plan", "DC cable routing and protection", "Inverter-side connection planning", "System testing and handover guidance"], commonNeeds: ["A new rooftop solar system", "Additional compatible panels", "A safer or cleaner panel layout", "Planning before equipment purchase"] },
  "solar/system-setup": { category: "solar", title: "Solar Connection and Setup", imageType: "install", summary: "Organised connection, configuration and commissioning of compatible solar equipment.", overview: "Correct setup depends on panel strings, inverter type, protection devices, battery arrangement and the property electrical system.", includes: ["Equipment compatibility review", "DC and AC connection inspection", "Inverter configuration support", "Protection and isolation checks", "Startup testing"], commonNeeds: ["New equipment awaiting setup", "A disconnected or relocated system", "Settings requiring review", "Unclear protection arrangement"] },
  "solar/repair": { category: "solar", title: "Solar System Repair and Diagnostics", imageType: "repair", summary: "Structured fault finding for low output, shutdowns and solar-system warnings.", overview: "Solar faults can originate from panels, connectors, cables, protection devices, inverter settings or batteries. Diagnosis isolates the likely cause before repair is recommended.", includes: ["Fault-history review", "Visible cable and connector inspection", "Inverter warning review", "Protection-device checks", "Findings and recommended action"], commonNeeds: ["Unexpected low generation", "Inverter warning or shutdown", "Intermittent operation", "Post-weather system concern"] },
  "solar/inverter-battery": { category: "solar", title: "Inverter and Battery Services", imageType: "repair", summary: "Assessment and support for compatible inverters, backup batteries and connections.", overview: "Performance depends on load, battery type and age, ventilation, connections and compatible charging settings.", includes: ["Inverter status review", "Battery connection inspection", "Charging-setting review", "Backup-load discussion", "Safe-use guidance"], commonNeeds: ["Reduced backup duration", "Battery charging issue", "Inverter alarm or error", "Settings after battery replacement"] },
  "solar/maintenance": { category: "solar", title: "Solar Panel Maintenance", imageType: "install", summary: "Routine visual checks, cleaning and performance-focused solar maintenance.", overview: "Dust, shade, loose visible fittings and blocked equipment ventilation can affect a system. Scope depends on safe roof access and installed equipment.", includes: ["Panel-surface review", "Accessible mounting and cable check", "Safe cleaning where agreed", "Inverter ventilation check", "Visible issue report"], commonNeeds: ["Dust or debris on panels", "Seasonal performance review", "Post-weather inspection", "Routine system care"] },
  "solar/panel-cleaning": { category: "solar", title: "Solar Panel Cleaning & Washing", imageType: "install", customImage: "/images/services/solar-panel-cleaning.jpg", customAlt: "Technicians carefully cleaning dusty rooftop solar panels in Lahore", summary: "Controlled cleaning for dust, dirt, bird droppings and surface buildup on Lahore rooftop panels.", overview: "Solar panels installed on Lahore rooftops are regularly exposed to dust, pollution, bird droppings, leaves and changing weather. This buildup can reduce the sunlight reaching panel cells. We inspect panel condition, rooftop access and visible electrical components before using suitable tools and controlled cleaning methods. Requirements depend on panel quantity, accessibility, dust level and mounting condition, so the final quotation follows a complete scope review.", includes: ["Initial visual inspection", "Dust and surface-buildup assessment", "Safe rooftop-access review", "Controlled solar panel washing", "Soft-brush panel cleaning", "Bird-dropping and loose-dirt removal", "Cleaning around accessible panel edges", "Basic mounting-structure inspection", "Visible cable-condition check", "Final visual review"], commonNeeds: ["Visible dust layer", "Bird droppings", "Leaves or surface debris", "Reduced production compared with normal performance", "Panels not cleaned for an extended period", "Cleaning before a system inspection"] },
  "solar/system-design": { category: "solar", title: "Solar System Design & Planning", imageType: "install", customImage: "/images/services/solar-system-design.jpg", customAlt: "Solar engineer planning a Lahore rooftop system with a homeowner", summary: "Practical solar planning around property usage, rooftop space, equipment and backup requirements.", overview: "A successful solar installation begins with proper planning. Energy usage, available rooftop space, sunlight exposure, shading, inverter requirements, battery preferences and the existing electrical setup all matter. We organise these requirements, review expected usage and prepare a suitable preliminary system direction. Final equipment selection and installation planning remain subject to site inspection, technical calculations and compatibility.", includes: ["Energy-requirement discussion", "Available electricity-bill review", "Rooftop-space assessment", "Panel-placement planning", "Basic shading considerations", "Solar panel quantity estimation", "Inverter-capacity considerations", "Battery and backup requirements", "Existing electrical-system review", "Cable-routing considerations", "Protection and earthing considerations", "Preliminary system layout", "Installation-scope planning"], commonNeeds: ["Planning a new home solar system", "Reviewing electricity usage and bills", "Comparing rooftop placement options", "Planning daytime and backup loads", "Including an existing inverter or battery", "Preparing before equipment purchase"] },
  "solar/troubleshooting": { category: "solar", title: "Solar Panel Troubleshooting", imageType: "repair", customImage: "/images/services/solar-troubleshooting.jpg", customAlt: "Technician troubleshooting solar inverter and rooftop connections in Lahore", summary: "Structured diagnosis for low production, inverter errors, charging issues and unexpected shutdowns.", overview: "Solar faults may involve panels, wiring, connectors, protection devices, the inverter, batteries or configuration. Troubleshooting begins with the reported symptoms and an inspection of accessible components, inverter indicators and battery behaviour. Not every fault requires equipment replacement, but repair recommendations can only follow diagnosis and compatibility checks.", includes: ["System and fault-history review", "Inverter and monitoring-information review", "Accessible panel inspection", "Connector and cable checks", "Protection-device assessment", "Inverter behaviour assessment", "Battery charging and backup review", "Likely fault-area identification", "Repair or replacement explanation", "Testing after approved work"], commonNeeds: ["Low solar production", "Unexpected system shutdown", "Inverter error messages", "Battery not charging correctly", "Weak backup duration", "Solar power not reaching selected loads", "Loose or damaged connectors", "Changeover or monitoring problems"] },
  "electrical/new-wiring": { category: "electrical", title: "New Electrical Wiring", imageType: "install", summary: "Planned wiring for new rooms, renovations, shops and property extensions.", overview: "New wiring starts with intended loads, room use, outlet positions, circuit separation and distribution-board capacity.", includes: ["Point and load review", "Circuit and route planning", "Cable and conduit scope", "DB connection planning", "Testing before handover"], commonNeeds: ["New construction or room addition", "Kitchen or office renovation", "Additional power points", "Dedicated equipment circuit"] },
  "electrical/rewiring": { category: "electrical", title: "Electrical Rewiring and Upgrades", imageType: "install", summary: "Replacement and improvement of ageing, damaged or unsuitable property wiring.", overview: "Rewiring scope depends on cable condition, circuit loading, concealed routes, distribution equipment and renovation extent.", includes: ["Wiring condition review", "Circuit and load assessment", "Replacement-route planning", "Protection recommendations", "Completed-circuit testing"], commonNeeds: ["Old or deteriorated wiring", "Heating or burning smell", "Renovation requiring circuits", "Insufficient circuit capacity"] },
  "electrical/fault-repair": { category: "electrical", title: "Electrical Fault Finding and Repair", imageType: "repair", summary: "Systematic diagnosis for tripping, dead points, flickering and intermittent faults.", overview: "Electrical symptoms can have several causes. Testing narrows the issue before repair, replacement or circuit work is proposed.", includes: ["Symptom and history review", "Relevant circuit isolation", "Accessible connection checks", "Breaker and DB inspection", "Repair and retesting"], commonNeeds: ["Repeated breaker tripping", "Dead socket or light", "Flickering supply", "Heat, smell or sparking"] },
  "electrical/distribution-board": { category: "electrical", title: "Distribution Board and Breaker Work", imageType: "repair", summary: "Distribution-board organisation, breaker assessment and protection improvements.", overview: "The board is reviewed against connected circuits, expected loads, breaker condition, labelling and available space.", includes: ["DB and circuit review", "Breaker assessment", "Circuit identification", "Upgrade or replacement scope", "Functional checks"], commonNeeds: ["Damaged breaker", "Overcrowded board", "Unlabelled circuits", "New dedicated connection"] },
  "electrical/fixtures": { category: "electrical", title: "Switch, Socket and Fixture Repairs", imageType: "repair", summary: "Repair and replacement support for switches, sockets, lights and fans.", overview: "A faulty point may involve the fitting, termination, connected circuit or appliance. The affected point is checked before replacement.", includes: ["Fixture inspection", "Accessible connection check", "Replacement matching", "Fitting and alignment", "Function test"], commonNeeds: ["Loose or broken socket", "Faulty switch", "Light fitting replacement", "Fan connection issue"] },
  "ac/installation": { category: "ac", title: "AC Installation", imageType: "install", summary: "Split AC placement, mounting and connection planning for dependable operation.", overview: "Installation depends on unit placement, drainage, pipe route, wall condition, electrical supply and manufacturer requirements.", includes: ["Unit and location review", "Indoor and outdoor mounting", "Pipe, drain and cable route", "Electrical supply check", "Startup and cooling check"], commonNeeds: ["New split AC installation", "Post-renovation installation", "Compatible unit replacement", "Outdoor-unit repositioning"] },
  "ac/repair": { category: "ac", title: "AC Repair", imageType: "repair", summary: "Diagnosis for units that stop, trip, make noise or do not cool correctly.", overview: "Poor operation can relate to airflow, controls, electrical parts, sensors, refrigerant circuit or outdoor-unit condition.", includes: ["Symptom review", "Indoor and outdoor inspection", "Control and electrical checks", "Airflow and cooling assessment", "Repair and retest"], commonNeeds: ["Unit not starting", "Weak or warm airflow", "Noise or vibration", "Unexpected shutdown or tripping"] },
  "ac/maintenance": { category: "ac", title: "AC Maintenance and Servicing", imageType: "repair", summary: "Routine cleaning and checks to support airflow, cooling and dependable use.", overview: "Service scope follows unit condition and accessibility. Cleaning does not replace diagnosis when a separate fault is present.", includes: ["Filter and accessible coil cleaning", "Drain-path check", "Indoor and outdoor inspection", "Airflow observation", "Maintenance findings"], commonNeeds: ["Reduced airflow", "Dust or odour", "Pre-season service", "Routine care after heavy use"] },
  "ac/shifting": { category: "ac", title: "AC Removal and Shifting", imageType: "install", summary: "Careful removal, relocation planning and reinstallation of compatible AC equipment.", overview: "Shifting requires both locations to be reviewed along with pipe, cable, drainage, mounting and reusable materials.", includes: ["Old and new location review", "Controlled removal", "Mounting and route planning", "Reinstallation", "Startup and cooling check"], commonNeeds: ["Moving room or property", "Relocation during renovation", "Outdoor-unit repositioning", "Removal before construction"] },
  "ac/leakage-diagnosis": { category: "ac", title: "AC Leakage and Cooling Diagnosis", imageType: "repair", summary: "Focused assessment for water leakage, weak cooling and icing.", overview: "Leakage and poor cooling can result from restricted airflow, drainage, icing, installation condition or refrigerant-circuit faults.", includes: ["Leak and symptom review", "Filter, coil and airflow check", "Drain inspection", "Visible pipe and joint review", "Corrective-work scope"], commonNeeds: ["Indoor water dripping", "Ice on unit or pipe", "Weak cooling", "Continuous running without comfort"] },
  "home-appliances/refrigerator-repair": { category: "home-appliances", title: "Refrigerator & Freezer Repair", imageType: "repair", summary: "Careful diagnosis and repair for cooling, frost, leakage, noise and startup problems.", overview: "Refrigerator faults may involve airflow, temperature controls, door seals, drainage, fans, accessible wiring or the compressor start system. We diagnose the actual cause before recommending parts or repair work.", includes: ["Cooling and temperature assessment", "Door seal and airflow inspection", "Thermostat and control review", "Accessible fan and start-circuit checks", "Drain and visible wiring inspection", "Repair testing and care guidance"], commonNeeds: ["Fridge or freezer not cooling", "Excess frost or over-freezing", "Water leaking inside or outside", "Unusual noise or continuous running", "Unit not starting", "Damaged or loose door seal"] },
  "home-appliances/washing-machine-repair": { category: "home-appliances", title: "Washing Machine Repair", imageType: "repair", summary: "Fault finding for machines that do not start, fill, drain, spin or complete a wash cycle.", overview: "Washing-machine issues can come from the inlet, drainage, door lock, controls, drive system, pump, hoses or electrical connections. Inspection helps separate a serviceable fault from a part that needs replacement.", includes: ["Cycle and symptom review", "Water inlet and hose inspection", "Drain pump and filter checks", "Door lock and control assessment", "Spin, vibration and noise review", "Leak test and operational retest"], commonNeeds: ["Machine not starting", "Water not filling or draining", "Drum not spinning", "Leakage during a cycle", "Excess vibration or noise", "Door not locking or opening"] },
  "home-appliances/microwave-repair": { category: "home-appliances", title: "Microwave Oven Repair", imageType: "repair", summary: "Safe diagnosis for microwave power, heating, control, door and turntable faults.", overview: "Microwaves contain high-voltage components even after being unplugged. Our inspection covers the reported symptom, accessible controls, door-interlock operation and heating behaviour without unsafe customer disassembly.", includes: ["Power and control assessment", "Door and interlock inspection", "Turntable and internal-light checks", "Heating-performance diagnosis", "Visible wiring and fuse review", "Safe functional testing"], commonNeeds: ["Microwave has no power", "Food is not heating", "Sparking or unusual smell", "Turntable not rotating", "Door not closing correctly", "Buttons or display not responding"] },
  "home-appliances/water-dispenser-repair": { category: "home-appliances", title: "Water Dispenser Repair", imageType: "repair", summary: "Repair support for cooling, heating, leakage, noise and dispensing problems.", overview: "A dispenser problem may relate to the water path, taps, thermostat, cooling or heating system, switches, controls or accessible wiring. The unit is inspected before repair options are confirmed.", includes: ["Cooling and heating checks", "Tap and water-flow inspection", "Leak-source assessment", "Switch and thermostat review", "Accessible electrical checks", "Operational and leak retest"], commonNeeds: ["Water is not cooling", "Hot-water function not working", "Water leaking from the unit", "Tap or flow problem", "Unusual operating noise", "Dispenser not powering on"] },
  "home-appliances/oven-cooking-range-repair": { category: "home-appliances", title: "Electric Oven & Cooking Range Repair", imageType: "repair", summary: "Diagnosis for electric ovens and cooking ranges with heating, control or door problems.", overview: "Electric oven performance depends on the elements, controls, thermostat, internal wiring, door seal and safe power supply. We assess the fault and explain the suitable repair scope before work begins.", includes: ["Heating-element assessment", "Control and thermostat checks", "Door, hinge and seal inspection", "Accessible wiring review", "Uneven-heating diagnosis", "Temperature and function retest"], commonNeeds: ["Oven not heating", "Uneven or weak heating", "Element not switching on", "Control or thermostat issue", "Door not closing properly", "Unexpected tripping or smell"] },
  "home-appliances/dishwasher-repair": { category: "home-appliances", title: "Dishwasher Repair", imageType: "repair", summary: "Practical repair for filling, draining, cleaning, leakage and drying issues.", overview: "Dishwasher faults can involve the inlet, pump, filter, spray arms, drain, heater, door latch or controls. A structured check identifies blockages, wear and electrical or mechanical faults.", includes: ["Fill and drain assessment", "Filter and spray-arm inspection", "Pump and hose checks", "Door latch and seal review", "Heating and drying assessment", "Leak and wash-cycle retest"], commonNeeds: ["Dishwasher not starting", "Water not entering or draining", "Dishes remain dirty", "Leakage around the door or base", "Unusual pump noise", "Poor heating or drying"] },
};

const serviceAssetOverrides: Record<string, { image: string; alt: string }> = {
  "solar/system-design": { image: "/images/services/solar-system-design.webp", alt: "Solar engineer planning a rooftop system with a Lahore homeowner" },
  "solar/panel-installation": { image: "/images/solar-panel-installation-lahore.webp", alt: "Solar technicians installing rooftop panels in Lahore" },
  "solar/system-setup": { image: "/images/lahore-solar-technicians-hero.png", alt: "Solar technicians completing panel connections on a Lahore rooftop" },
  "solar/inverter-battery": { image: "/images/solar-inverter-repair-lahore.webp", alt: "Technician assessing a solar inverter and battery setup in Lahore" },
  "solar/troubleshooting": { image: "/images/services/solar-troubleshooting.webp", alt: "Technician troubleshooting solar inverter and rooftop connections in Lahore" },
  "solar/repair": { image: "/images/solar-inverter-diagnostics-lahore.png", alt: "Technician diagnosing a solar inverter system in Lahore" },
  "solar/panel-cleaning": { image: "/images/services/solar-panel-cleaning.webp", alt: "Technicians carefully washing dusty rooftop solar panels in Lahore" },
  "solar/maintenance": { image: "/images/solar-panel-maintenance-lahore.png", alt: "Technicians inspecting and maintaining rooftop solar panels in Lahore" },
  "electrical/new-wiring": { image: "/images/electrical-wiring-lahore.webp", alt: "Electrician installing organised new wiring in a Lahore property" },
  "electrical/rewiring": { image: "/images/electrical-conduit-installation-lahore.png", alt: "Electrician replacing wiring and conduit during a Lahore renovation" },
  "electrical/fault-repair": { image: "/images/electrical-fault-repair-lahore.webp", alt: "Electrician diagnosing an electrical fault with test equipment in Lahore" },
  "electrical/distribution-board": { image: "/images/electrical-db-testing-lahore.png", alt: "Electrician testing an organised distribution board in Lahore" },
  "electrical/fixtures": { image: "/images/lahore-electrical-service.png", alt: "Electrician repairing residential switches and fixtures in Lahore" },
  "ac/installation": { image: "/images/ac-installation-lahore.webp", alt: "Technician installing a split AC unit in a Lahore home" },
  "ac/repair": { image: "/images/ac-repair-service-lahore.webp", alt: "Technician diagnosing an opened split AC unit in Lahore" },
  "ac/maintenance": { image: "/images/ac-indoor-maintenance-lahore.png", alt: "Technician cleaning and maintaining an indoor AC unit in Lahore" },
  "ac/shifting": { image: "/images/hero/ac-services-hero.png", alt: "Technicians safely removing and reinstalling a split AC unit in Lahore" },
  "ac/leakage-diagnosis": { image: "/images/ac-outdoor-diagnostics-lahore.png", alt: "Technician diagnosing AC cooling performance at an outdoor unit in Lahore" },
  "home-appliances/refrigerator-repair": { image: "/images/home-appliances/refrigerator-repair.webp", alt: "Pakistani technician diagnosing a refrigerator in a Lahore kitchen" },
  "home-appliances/washing-machine-repair": { image: "/images/home-appliances/washing-machine-repair.webp", alt: "Pakistani technician repairing a washing machine in Lahore" },
  "home-appliances/microwave-repair": { image: "/images/home-appliances/microwave-repair.webp", alt: "Pakistani technician safely diagnosing a microwave oven in Lahore" },
  "home-appliances/water-dispenser-repair": { image: "/images/home-appliances/water-dispenser-repair.webp", alt: "Pakistani technician repairing a water dispenser in Lahore" },
  "home-appliances/oven-cooking-range-repair": { image: "/images/home-appliances/oven-cooking-range-repair.webp", alt: "Pakistani technician repairing an electric oven and cooking range in Lahore" },
  "home-appliances/dishwasher-repair": { image: "/images/home-appliances/dishwasher-repair.webp", alt: "Pakistani technician servicing a dishwasher in a Lahore kitchen" },
};

export const serviceDetails: Record<string, ServiceDetail & { checks: readonly string[] }> = Object.fromEntries(Object.entries(entries).map(([key, entry]) => {
  const category = categoryData[entry.category];
  const generated = entry.category === "solar"
    ? [{ src: "/images/solar-panel-maintenance-lahore.png", alt: "Pakistani technicians cleaning and inspecting rooftop solar panels in Lahore" }, { src: "/images/solar-inverter-diagnostics-lahore.png", alt: "Pakistani technician diagnosing a solar inverter and battery system in Lahore" }]
    : entry.category === "electrical"
      ? [{ src: "/images/electrical-conduit-installation-lahore.png", alt: "Pakistani electrician installing conduit during a Lahore home renovation" }, { src: "/images/electrical-db-testing-lahore.png", alt: "Pakistani electrician testing a residential distribution board in Lahore" }]
      : entry.category === "ac"
        ? [{ src: "/images/ac-indoor-maintenance-lahore.png", alt: "Pakistani AC technician maintaining an indoor split AC unit in Lahore" }, { src: "/images/ac-outdoor-diagnostics-lahore.png", alt: "Pakistani AC technician diagnosing an outdoor condenser on a Lahore rooftop" }]
        : [{ src: "/images/home-appliances/category-hero.webp", alt: "Home appliance repair services for Lahore households" }, { src: "/images/home-appliances/washing-machine-repair.webp", alt: "Pakistani technician inspecting a washing machine in Lahore" }];
  const asset = serviceAssetOverrides[key];
  const primaryImage = asset?.image || entry.customImage || (entry.imageType === "install" ? category.installImage : category.repairImage);
  const primaryAlt = asset?.alt || entry.customAlt || (entry.imageType === "install" ? category.installAlt : category.repairAlt);
  const gallery = [{ src: primaryImage, alt: primaryAlt }, ...generated, { src: entry.imageType === "install" ? category.repairImage : category.installImage, alt: entry.imageType === "install" ? category.repairAlt : category.installAlt }];
  return [key, { ...entry, image: primaryImage, imageAlt: primaryAlt, gallery, checks: category.checks }];
}));

export const serviceProcess = [["Share the requirement", "Explain the issue, property type, area and useful history or photos."], ["Inspect and diagnose", "The relevant site, equipment, connections and visible conditions are reviewed."], ["Confirm the scope", "Recommended work, materials and quotation basis are explained before work starts."], ["Complete the work", "The agreed service is carried out with attention to access and surrounding finishes."], ["Test and hand over", "Operation is checked and relevant care or next-step guidance is shared."]] as const;
